# Generated by Django 4.0.1 on 2022-01-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
